import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { cookies } from "next/headers";
import { NextAuthProvider } from "@/components/next-auth-provider";
import StoreProvider from "./StoreProvider";
import { getUserSession } from "@/lib/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function getToken() {
  const cookieStore = cookies();
  return cookieStore?.get("__Secure-next-auth.session-token")?.value || "";
  // return cookieStore?.get("next-auth.session-token")?.value || "";
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <NextAuthProvider user={user} token={getToken()}>
            {children}
          </NextAuthProvider>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
